package anim

import (
	"math"
	"strings"
)

//go:generate go run meshgen.go

// region tags a baked point with the mesh material group it came from, so the
// renderer can color the EVA-01 head iconically (green crest, glowing eyes, red
// accents) instead of one flat ramp.
type region uint8

const (
	regionArmor region = iota
	regionGreen
	regionEyes
	regionBlackEyes
	regionRed
	regionBrown
)

// bakedPoint is one decimated surface sample of the EVA-01 head: position,
// outward normal, and its material region. The cloud lives in evahead_data.go
// (generated by meshgen.go), centered on the origin and scaled to max-radius 1.
type bakedPoint struct {
	X, Y, Z    float32
	NX, NY, NZ float32
	R          region
}

// Rest orientation: the pose the head holds at frame 0, before the per-frame spin
// advances it — the EVA-01 left profile from the reference image. The blade runs
// along the model's crown axis, so to lay the blade toward the horizontal-LEFT we
// pitch the crown back (restPitch ~ -pi/2) and yaw to profile (restYaw = +pi/2),
// which also brings the face/eye mass to the center-right. restRoll stays 0 (no
// screen-plane roll). Because the spin is a yaw about the vertical axis and the
// blade keeps a constant slight-up component under that yaw, the blade then
// sweeps left<->right (staying up, never tumbling down) as the head turns. Tuned
// by eye against the reference image and vhs frame dumps.
const (
	restPitch = -1.40       // pitch the crown back so the blade lays toward horizontal
	restRoll  = 0.0         // no screen-plane roll (crown is not tipped in the screen plane)
	restYaw   = math.Pi / 2 // yaw to the left profile: face center-right, blade projects LEFT
)

// aspectY compensates for terminal cells being ~2x taller than wide so the head
// reads round, not stretched.
const aspectY = 0.5

// spinPerFrame is the per-frame yaw advance, about the vertical axis, layered on
// top of restYaw: the head turns and the horn sweeps left -> toward-viewer ->
// right as it rotates (~3.5s per turn at ~14fps in EVA mode).
const spinPerFrame = 0.16

// light is the fixed view-space light direction (upper-front-left).
var light = normalize3(-0.30, 0.55, 0.80)

// Head renders the rotating EVA-01 head into a w x h grid and returns h lines,
// each exactly w visible columns (indexed-256 SGR, reset at line end). accent
// tints only the armor; the green crest, eyes, and red accents keep their
// iconic colors. frame drives the rotation.
func Head(w, h, frame, accent int) []string {
	chars, colors, ok := headGrid(w, h, frame, accent)
	if !ok {
		return blankLines(w, h)
	}
	return composeLines(w, h, chars, colors)
}

// headSS is the supersample factor: the cloud is z-buffered into a grid headSS
// times finer in each axis, then each headSS x headSS block is resolved to one
// output cell by its nearest-Z lit sub-sample. This anti-aliases the silhouette
// and — crucially at the small docked size — fills the gaps a sparse point cloud
// would otherwise leave between samples.
const headSS = 2

// headGrid renders the head into per-cell rune + color buffers (z-buffered and
// region-shaded). It is the shared core of Head (which styles it into lines) and
// the intro (which blits it into its own grid). ok is false when the grid is too
// small or the cloud is empty.
func headGrid(w, h, frame, accent int) (chars []rune, colors []int, ok bool) {
	if w < 6 || h < 4 || len(evaHeadPoints) == 0 {
		return nil, nil, false
	}

	armorRamp := rampForAccent(accent)

	// Supersampled buffers: render the cloud at headSS x resolution, downsample
	// at the end.
	sw, sh := w*headSS, h*headSS

	// The cloud has radius <= 1, so fit radius 1 to the (supersampled) grid
	// (height usually binds because cells are tall), keeping the aspect
	// correction.
	sx := float64(sw-1) / 2
	sy := sx * aspectY
	if maxSy := float64(sh-1) / 2; sy > maxSy {
		sy = maxSy
		sx = sy / aspectY
	}
	cx := float64(sw-1) / 2
	cy := float64(sh-1) / 2

	size := sw * sh
	depth := make([]float64, size)
	scharBuf := make([]rune, size)
	scolorBuf := make([]int, size)
	for i := range depth {
		depth[i] = math.Inf(-1)
		scharBuf[i] = ' '
		scolorBuf[i] = -1
	}

	// Start from the left-profile rest pose (restYaw) and spin about the vertical
	// axis from there, so the head turns and the horn sweeps around.
	theta := restYaw + float64(frame)*spinPerFrame
	sinT, cosT := math.Sin(theta), math.Cos(theta)
	sinP, cosP := math.Sin(restPitch), math.Cos(restPitch)
	sinR, cosR := math.Sin(restRoll), math.Cos(restRoll)

	rot := func(x, y, z float64) (float64, float64, float64) {
		// Rest roll (Z, zero here), rest pitch (X), then the yaw (Y) that carries
		// both the left-profile rest pose and the per-frame spin. Yaw is about the
		// vertical axis, so the crown stays up and the head reads as turning.
		x, y = x*cosR-y*sinR, x*sinR+y*cosR
		y, z = y*cosP-z*sinP, y*sinP+z*cosP
		x, z = x*cosT+z*sinT, -x*sinT+z*cosT
		return x, y, z
	}

	for _, p := range evaHeadPoints {
		// Reorient the mesh into the renderer's pose, then rotate.
		mx, my, mz := orient(float64(p.X), float64(p.Y), float64(p.Z))
		x, y, z := rot(mx, my, mz)
		nmx, nmy, nmz := orient(float64(p.NX), float64(p.NY), float64(p.NZ))
		nx, ny, nz := rot(nmx, nmy, nmz)

		col := int(math.Round(cx + sx*x))
		row := int(math.Round(cy - sy*y))
		if col < 0 || col >= sw || row < 0 || row >= sh {
			continue
		}
		idx := row*sw + col

		if p.R == regionEyes {
			// The eyes are the iconic gaze. Cull them only when they face away;
			// when they face the viewer, bias them forward so the surrounding
			// armor shell (now dense) can never occlude them — they always read
			// as the unit's "live" eyes, at any render size.
			if nz < -0.05 {
				continue
			}
			z += eyeDepthBias
		} else if nz < 0 {
			// Back-face cull (closed surface) keeps the silhouette clean.
			continue
		}
		if z <= depth[idx] {
			continue
		}

		lum := nx*light.x + ny*light.y + nz*light.z
		if lum < 0 {
			lum = 0
		}
		ch, color := shade(p.R, lum, armorRamp)
		depth[idx] = z
		scharBuf[idx] = ch
		scolorBuf[idx] = color
	}

	// Downsample: each output cell takes the nearest-Z lit sub-sample in its
	// headSS x headSS block. Front-facing eyes were depth-biased above, so they
	// naturally win their block and the gaze never dims out.
	chars = make([]rune, w*h)
	colors = make([]int, w*h)
	for r := 0; r < h; r++ {
		for c := 0; c < w; c++ {
			bestZ := math.Inf(-1)
			bestCh := ' '
			bestColor := -1
			for dy := 0; dy < headSS; dy++ {
				for dx := 0; dx < headSS; dx++ {
					si := (r*headSS+dy)*sw + (c*headSS + dx)
					if scharBuf[si] == ' ' {
						continue
					}
					if depth[si] > bestZ {
						bestZ = depth[si]
						bestCh = scharBuf[si]
						bestColor = scolorBuf[si]
					}
				}
			}
			chars[r*w+c] = bestCh
			colors[r*w+c] = bestColor
		}
	}

	return chars, colors, true
}

// eyeDepthBias is the forward Z offset applied to front-facing eye samples so
// the dense armor shell never occludes the EVA-01's glowing eyes.
const eyeDepthBias = 0.6

// shade maps a point's region + luminance to a glyph and an indexed color.
// Eyes always glow bright green; the armor follows the phase accent ramp.
func shade(r region, lum float64, armorRamp []int) (rune, int) {
	switch r {
	case regionEyes:
		return '@', eyeGreen
	case regionBlackEyes:
		return rampChar(lum * 0.6), steelRamp[rampIndex(lum*0.5, len(steelRamp))]
	case regionGreen:
		return rampChar(lum), phosphorRamp[rampIndex(lum, len(phosphorRamp))]
	case regionRed:
		return rampChar(lum), redRamp[rampIndex(lum, len(redRamp))]
	case regionBrown:
		return rampChar(lum), amberRamp[rampIndex(lum, len(amberRamp))]
	default: // armor
		return rampChar(lum), armorRamp[rampIndex(lum, len(armorRamp))]
	}
}

// orient remaps the baked mesh's object axes into the renderer's axes (up +Y,
// forward +Z, right +X). The mesh is mirror-symmetric in its Y (left-right),
// long in -X (crown/horn up), and faces +Z; this maps model Y->X, model -X->Y,
// model Z->Z. Locked by eye against the calibration dump.
var orient = func(x, y, z float64) (float64, float64, float64) {
	return y, -x, z
}

// composeLines turns the z-buffered char/color grid into styled lines,
// coalescing color runs and resetting at blanks and line end. Every line has
// exactly w visible columns.
func composeLines(w, h int, chars []rune, colors []int) []string {
	lines := make([]string, h)
	for r := 0; r < h; r++ {
		var b strings.Builder
		cur := -1
		for c := 0; c < w; c++ {
			idx := r*w + c
			if chars[idx] == ' ' {
				if cur != -1 {
					b.WriteString(reset)
					cur = -1
				}
				b.WriteByte(' ')
				continue
			}
			if colors[idx] != cur {
				b.WriteString(sgr(colors[idx]))
				cur = colors[idx]
			}
			b.WriteRune(chars[idx])
		}
		if cur != -1 {
			b.WriteString(reset)
		}
		lines[r] = b.String()
	}
	return lines
}

// rampChar maps a [0,1] luminance to a glyph, reserving the leading space for
// empty cells so a lit point never blanks out.
func rampChar(lum float64) rune {
	n := len(charRamp)
	i := 1 + int(lum*float64(n-2)+0.5)
	if i < 1 {
		i = 1
	}
	if i > n-1 {
		i = n - 1
	}
	return rune(charRamp[i])
}

// rampIndex maps a [0,1] luminance to an index into an n-entry color ramp.
func rampIndex(lum float64, n int) int {
	i := int(lum*float64(n-1) + 0.5)
	if i < 0 {
		i = 0
	}
	if i > n-1 {
		i = n - 1
	}
	return i
}

type vec3 struct{ x, y, z float64 }

func normalize3(x, y, z float64) vec3 {
	m := math.Sqrt(x*x + y*y + z*z)
	if m == 0 {
		return vec3{0, 0, 1}
	}
	return vec3{x / m, y / m, z / m}
}

// blankLines returns h empty lines, each w spaces wide.
func blankLines(w, h int) []string {
	if w < 0 {
		w = 0
	}
	if h < 0 {
		h = 0
	}
	row := strings.Repeat(" ", w)
	lines := make([]string, h)
	for i := range lines {
		lines[i] = row
	}
	return lines
}
