#!/usr/bin/env bash
#
# Render the Homebrew formula for council from a release's checksums file.
#
# Usage: render_formula.sh <version> <checksums.txt> [class_name]
#   <version>        release version, with or without a leading "v" (e.g. v0.2.0)
#   <checksums.txt>  sha256sum-format file listing the release archives
#
# The output (a complete Formula/council.rb) is written to stdout.
set -euo pipefail

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
  echo "usage: $0 <version> <checksums.txt> [class_name]" >&2
  exit 2
fi

version="${1#v}"
checksums="$2"
formula_class="${3:-Council}"
repo="umutarmut38/council"
base="https://github.com/${repo}/releases/download/v${version}"

sha() {
  local file="council_v${version}_$1.tar.gz"
  local value
  value="$(awk -v f="$file" '$2 == f { print $1 }' "$checksums")"
  if [ -z "$value" ]; then
    echo "missing checksum for $file in $checksums" >&2
    exit 1
  fi
  printf '%s' "$value"
}

darwin_arm="$(sha darwin_arm64)"
darwin_amd="$(sha darwin_amd64)"
linux_arm="$(sha linux_arm64)"
linux_amd="$(sha linux_amd64)"

cat <<EOF
# This file is generated by packaging/homebrew/render_formula.sh in
# https://github.com/${repo}. Do not edit by hand.
class ${formula_class} < Formula
  desc "Multi-agent orchestration TUI for competing AI coding-agent CLIs"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/council_v${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm}"
    end
    on_intel do
      url "${base}/council_v${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/council_v${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${base}/council_v${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd}"
    end
  end

  def install
    bin.install "council"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/council version")
  end
end
EOF
