package pricing

// builtinAliases is ported verbatim from codeburn src/models.ts BUILTIN_ALIASES
// (MIT, (c) 2026 AgentSeal). Maps provider-emitted model-name variants to
// canonical names resolved before price lookup. See NOTICE. Regenerate from a
// codeburn checkout; do not hand-edit.
var builtinAliases = map[string]string{
	"anthropic--claude-4.6-opus":           "claude-opus-4-6",
	"anthropic--claude-4.6-sonnet":         "claude-sonnet-4-6",
	"anthropic--claude-4.5-opus":           "claude-opus-4-5",
	"anthropic--claude-4.5-sonnet":         "claude-sonnet-4-5",
	"anthropic--claude-4.5-haiku":          "claude-haiku-4-5",
	"claude-sonnet-4.6":                    "claude-sonnet-4-6",
	"claude-sonnet-4.5":                    "claude-sonnet-4-5",
	"claude-opus-4.7":                      "claude-opus-4-7",
	"claude-opus-4.6":                      "claude-opus-4-6",
	"claude-opus-4.5":                      "claude-opus-4-5",
	"cursor-auto":                          "claude-sonnet-4-5",
	"cursor-agent-auto":                    "claude-sonnet-4-5",
	"copilot-auto":                         "claude-sonnet-4-5",
	"copilot-openai-auto":                  "gpt-5.3-codex",
	"copilot-anthropic-auto":               "claude-sonnet-4-5",
	"ibm-bob-auto":                         "claude-sonnet-4-5",
	"kiro-auto":                            "claude-sonnet-4-5",
	"cline-auto":                           "claude-sonnet-4-5",
	"openclaw-auto":                        "claude-sonnet-4-5",
	"warp-auto-efficient":                  "gpt-5.3-codex",
	"warp-auto-powerful":                   "claude-opus-4-6",
	"grok-build":                           "grok-build-0.1",
	"GPT-5.3 Codex (low reasoning)":        "gpt-5.3-codex",
	"GPT-5.3 Codex (medium reasoning)":     "gpt-5.3-codex",
	"GPT-5.3 Codex (high reasoning)":       "gpt-5.3-codex",
	"GPT-5.3 Codex (extra high reasoning)": "gpt-5.3-codex",
	"Claude Sonnet 4.6":                    "claude-sonnet-4-6",
	"Claude Sonnet 4.5":                    "claude-sonnet-4-5",
	"Claude Haiku 4.5":                     "claude-haiku-4-5",
	"Claude Opus 4.6":                      "claude-opus-4-6",
	"claude-4-6-sonnet-high":               "claude-sonnet-4-6",
	"claude-4-6-sonnet-low":                "claude-sonnet-4-6",
	"claude-4-6-sonnet-medium":             "claude-sonnet-4-6",
	"claude-4-6-sonnet-high-fast":          "claude-sonnet-4-6",
	"claude-4-7-opus-xhigh":                "claude-opus-4-7",
	"claude-4-7-opus-xhigh-fast":           "claude-opus-4-7",
	"qwen-auto":                            "claude-sonnet-4-5",
	"kimi-auto":                            "kimi-k2-thinking",
	"kimi-code":                            "kimi-k2-thinking",
	"kimi-for-coding":                      "kimi-k2-thinking",
	"claude-4-sonnet":                      "claude-sonnet-4",
	"claude-4-sonnet-1m":                   "claude-sonnet-4",
	"claude-4-sonnet-thinking":             "claude-sonnet-4-5",
	"claude-4.5-sonnet":                    "claude-sonnet-4-5",
	"claude-4.5-sonnet-thinking":           "claude-sonnet-4-5",
	"claude-4.6-sonnet":                    "claude-sonnet-4-6",
	"claude-4.6-sonnet-high":               "claude-sonnet-4-6",
	"claude-4.6-sonnet-low":                "claude-sonnet-4-6",
	"claude-4.6-sonnet-thinking":           "claude-sonnet-4-6",
	"claude-4.6-sonnet-high-thinking":      "claude-sonnet-4-6",
	"claude-4-opus":                        "claude-opus-4",
	"claude-4.5-opus":                      "claude-opus-4-5",
	"claude-4.5-opus-high":                 "claude-opus-4-5",
	"claude-4.5-opus-low":                  "claude-opus-4-5",
	"claude-4.5-opus-medium":               "claude-opus-4-5",
	"claude-4.5-opus-high-thinking":        "claude-opus-4-5",
	"claude-4.6-opus":                      "claude-opus-4-6",
	"claude-4.6-opus-fast-mode":            "claude-opus-4-6",
	"claude-4.6-opus-high":                 "claude-opus-4-6",
	"claude-4.6-opus-low":                  "claude-opus-4-6",
	"claude-4.6-opus-medium":               "claude-opus-4-6",
	"claude-4.6-opus-high-thinking":        "claude-opus-4-6",
	"claude-4.7-opus":                      "claude-opus-4-7",
	"claude-opus-4-7-thinking-high":        "claude-opus-4-7",
	"claude-4.5-haiku":                     "claude-haiku-4-5",
	"claude-4.6-haiku":                     "claude-haiku-4-5",
	"composer-1":                           "claude-sonnet-4-5",
	"composer-1.5":                         "claude-sonnet-4-5",
	"composer-2":                           "claude-sonnet-4-6",
	"gpt-5-fast":                           "gpt-5",
	"gpt-4.1":                              "gpt-4.1",
	"gpt-5.2-low":                          "gpt-5",
	"gpt-5.1-codex-high":                   "gpt-5.3-codex",
	"gemini-3.1-pro":                       "gemini-3.1-pro-preview",
	"gemini-3-flash":                       "gemini-3-flash-preview",
	"gemini-3.1-pro-high":                  "gemini-3.1-pro-preview",
	"gemini-3.1-pro-low":                   "gemini-3.1-pro-preview",
	"gemini-3-flash-agent":                 "gemini-3-flash-preview",
	"gemini-3.5-flash-high":                "gemini-3.5-flash",
	"gemini-3.5-flash-medium":              "gemini-3.5-flash",
	"gemini-3.5-flash-low":                 "gemini-3.5-flash",
	"Gemini 3.5 Flash (High)":              "gemini-3.5-flash",
	"Gemini 3.5 Flash (Medium)":            "gemini-3.5-flash",
	"Gemini 3.5 Flash (Low)":               "gemini-3.5-flash",
	"gemini-3-pro":                         "gemini-3-pro-preview",
	"gemini-3.1-flash-image":               "gemini-3.1-flash-image-preview",
	"gemini-3.1-flash-lite":                "gemini-3.1-flash-lite-preview",
	"GLM-5.2":                              "glm-5p1",
	"glm-5.2":                              "glm-5p1",
}
